### ISSUE TITLE
1.3.0 版本 字体名称在figma中显示?????，没有调用到英文名

### ISSUE THREAD

**Issue by txtwork** [Skr-ZERO/MaokenAssortedSans#3]
如题

**Comment by txtwork** [comment]
MaokenAssortedSans.ttf 版本，其他未测试

**Comment by Skr-ZERO** [comment]
[修复.zip](https://github.com/Skr-ZERO/MaokenAssortedSans/files/9950029/default.zip)

**Comment by Skr-ZERO** [comment]
试试这个。

**Comment by txtwork** [comment]
> 试试这个。

ttf 和 otf 都试了，还是一样

![image](https://user-images.githubusercontent.com/11283300/200278006-e0bc1b04-dabb-45b0-a36f-90827103e6a5.png)

**Comment by txtwork** [comment]
抱歉，标题描述的有错误，我重新验证了，1.2.0也是同样的问题。只有1.0.0是正常的

**Comment by Skr-ZERO** [comment]
[修改.zip](https://github.com/Skr-ZERO/MaokenAssortedSans/files/9950610/default.zip)

**Comment by txtwork** [comment]
> [修改.zip](https://github.com/Skr-ZERO/MaokenAssortedSans/files/9950610/default.zip) 这回还有问题我也没招了。

Perfect，完美

![image](https://user-images.githubusercontent.com/11283300/200290882-a948a283-67d4-4e7f-8d56-db3a409460fa.png)
