### ISSUE TITLE
無法正常顯示繁體中文「鏟」

### ISSUE THREAD

**Issue by Linnest2020** [Skr-ZERO/MaokenAssortedSans#4]
使用版本:  MaokenAssortedSans-Lite.ttf  [version 1.40, 20230117](https://github.com/Skr-ZERO/MaokenAssortedSans/releases/tag/v1.40)

如圖, 
![4I(K2ZYY}SAYHCUY FZLM_1](https://github.com/Skr-ZERO/MaokenAssortedSans/assets/116415445/675b68f4-2415-4cd6-adcb-783dbd8de781)
原圖應為「鍋鏟*」, 但是無法正常顯示, 更換版本到最新版仍然無效。

**Comment by Skr-ZERO** [comment]
繁体中文的版本正在制作中，需要很长一段时间才能做好，还请耐心等待。

**Comment by Skr-ZERO** [comment]
繁體中文的版本已經製作好試用版，歡迎下載使用。
https://github.com/Skr-ZERO/MaokenAssortedSans-TC/
