### ISSUE TITLE
字形竖排轴线问题。

### ISSUE THREAD

**Issue by zouchengjun** [Skr-ZERO/MaokenAssortedSans#5]
![M_TRLRPNEQ5B7FR_9N}20XJ](https://github.com/user-attachments/assets/0ebbfb43-be38-4959-9b5b-ef86ffb682f4)
![A(VE`J`GZW5FUGV9Z_$5CZK](https://github.com/user-attachments/assets/afba7f43-c194-4846-b0f3-5e87f0180c1f)
1.6版本部分字形的上下轴线有问题，竖排出现重叠的问题。

**Comment by Skr-ZERO** [comment]
已修复。
